DROP TABLE IF EXISTS meal;

CREATE TABLE meal (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    grams DOUBLE NOT NULL,
    kcal DOUBLE NOT NULL,
    carbs DOUBLE NOT NULL,
    protein DOUBLE NOT NULL,
    fat DOUBLE NOT NULL,
    user_id INT
);

ALTER TABLE ingredient ADD FOREIGN KEY (meal_id) REFERENCES meal(id);